ORMBundle\Entity\App:
    type: entity
    table: app
    indexes:
        id_store:
            columns:
                - id_store
        id_sqls:
            columns:
                - id_sqls
        id_type_projet:
            columns:
                - id_type_projet
        id_back_office:
            columns:
                - id_back_office
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        nom:
            type: string
            nullable: false
            length: 50
            options:
                fixed: false
        idstore:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: id_store
        idSqls:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: id_sqls
        idIps:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: id_ips
        idHosts:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: id_hosts
        idTypeProjet:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: id_type_projet
        idBackOffice:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: id_back_office
        idPageSpeed:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: id_page_speed
        idUrl:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: id_url
        Priority:
            type: integer
            nullable: true
            length: 6
            options:
                default : 1
                unsigned: false
            column: priority
        Expired:
            type: integer
            nullable: true
            length: 6
            options:
                default : 1
                unsigned: false
            column: expired
    oneToOne:
        urls:
            targetEntity: Urls
            joinColumn:
                name: id_url
                referencedColumnName: id
    manyToOne:
        store:
            targetEntity: Store
            joinColumn:
                name: id_store
                referencedColumnName: id
        sqls:
            targetEntity: Sqls
            joinColumn:
                name: id_sqls
                referencedColumnName: id
        ips:
            targetEntity: Ips
            joinColumn:
                name: id_ips
                referencedColumnName: id
        hosts:
            targetEntity: Hosts
            joinColumn:
                name: id_hosts
                referencedColumnName: id
        type_projet:
            targetEntity: TypeProjet
            joinColumn:
                name: id_type_projet
                referencedColumnName: id
        page_speed:
            targetEntity: PageSpeed
            joinColumn:
                name: id_page_speed
                referencedColumnName: id
        back_office:
            targetEntity: BackOffice
            joinColumn:
                name: id_back_office
                referencedColumnName: id
        link_site1:
            targetEntity: LinkSite
            joinColumn:
                name: id
                referencedColumnName: id_site1
        link_site2:
            targetEntity: LinkSite
            joinColumn:
                name: id
                referencedColumnName: id_site2
    oneToMany:
        link_category:
            targetEntity: LinkCategory
            mappedBy : id_site
        link_git:
            targetEntity: LinkGit
            mappedBy :  id_git
        link_bill:
            targetEntity: LinkBill
            mappedBy :  id_bill
    lifecycleCallbacks: {  }
