ORMBundle\Entity\Category:
    type: entity
    table: category
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        category:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        description:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
    oneToMany:
        link_category:
            targetEntity: LinkCategory
            mappedBy: id_category
    lifecycleCallbacks: {  }
