ORMBundle\Entity\Git:
    type: entity
    table: git
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        url:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        description:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
    oneToMany:
        link_git:
            targetEntity: LinkGit
            mappedBy: id_git
    lifecycleCallbacks: {  }
