ORMBundle\Entity\Other:
    type: entity
    table: other
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        title:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        url:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        description:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
    oneToMany:
        link_bill:
            targetEntity: LinkBill
            mappedBy: id_bill
    lifecycleCallbacks: {  }
