ORMBundle\Entity\SocialNetwork:
    type: entity
    table: social_network
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        nom:
            type: string
            nullable: false
            length: 50
            options:
                fixed: false
        login:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        password:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        prix:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        commentaire:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        url:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
                comment: 'url de login'
        mail:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
                comment: 'mail'
    lifecycleCallbacks: {  }
